### ISSUE TITLE
Want to donate

### ISSUE THREAD

**Issue by zazahunter** [RavEngine/RavEngine#17]
Hi, I wanted to contact you privately and also donate money.

**Comment by Ravbug** [comment]
Hi, I appreciate the gesture, but I do not accept monetary compensation. If you would like to support this project, please share it with your friends! \:D

Also, does the request need to be private? 

And, in the future, please use the [Discussions](https://github.com/RavEngine/RavEngine/discussions) section of this repository for non-bug-related things.

**Comment by zazahunter** [comment]
ah, well no worries i will close this now.
