### ISSUE TITLE
[BUG] Windows Build fails with MSVC

### ISSUE THREAD

**Issue by mPorst** [RavEngine/RavEngine#19]
# The Issues section is for bugs only. For questions or feature requests, please use the Discussions section: https://github.com/RavEngine/RavEngine/discussions

**Describe the bug**
In configure I see some PhysX related errors which state "No error", so I ignore them:
```
[cmake] CMake Error at deps/physx/physx/source/compiler/cmake/windows/CMakeLists.txt:116 (FILE):
[cmake]   FILE COPY cannot find "/bin//win.x86_64.vc141.mt/checked/PhysXGpu_64.dll":
[cmake]   No error.
```
In the build I then receive the following errors:

[build] C:\Users\xyz\source\repos\RavEngine\deps\RGL\deps\ShaderTranspiler\src\ShaderTranspiler.cpp(541,13): error C2760: syntax error: 'sourceBuffer' was unexpected here; expected ';' [C:\Users\xyz\source\repos\RavEngine\build\deps\RGL\deps\ShaderTranspiler\ShaderTranspiler.vcxproj]
[build] C:\Users\xyz\source\repos\RavEngine\deps\RGL\deps\ShaderTranspiler\src\ShaderTranspiler.cpp(566,13): error C2760: syntax error: 'reflectionBuffer' was unexpected here; expected ';' [C:\Users\xyz\source\repos\RavEngine\build\deps\RGL\deps\ShaderTranspiler\ShaderTranspiler.vcxproj]
[build] C:\Users\xyz\source\repos\RavEngine\deps\RGL\deps\ShaderTranspiler\src\ShaderTranspiler.cpp(577,3): error C2059: syntax error: ';' [C:\Users\xyz\source\repos\RavEngine\build\deps\RGL\deps\ShaderTranspiler\ShaderTranspiler.vcxproj]
[build] C:\Users\xyz\source\repos\RavEngine\deps\RGL\deps\ShaderTranspiler\src\ShaderTranspiler.cpp(619,3): error C3536: 'compileWithNewDxc': cannot be used before it is initialized [C:\Users\xyz\source\repos\RavEngine\build\deps\RGL\deps\ShaderTranspiler\ShaderTranspiler.vcxproj]
[build] C:\Users\xyz\source\repos\RavEngine\deps\RGL\deps\ShaderTranspiler\src\ShaderTranspiler.cpp(619,3): error C2064: term does not evaluate to a function taking 0 arguments [C:\Users\xyz\source\repos\RavEngine\build\deps\RGL\deps\ShaderTranspiler\ShaderTranspiler.vcxproj]

(there are more errors, but these are the first that occur and I want to avoid to spam my whole build log in here)

**To Reproduce**
This happens in the vanilla RavEngine from master on windows. I have no local changes

**System information**
- Target OS: Windows 11
- Development OS: Windows 11
- Engine commit number: b659474
- Compiler (if applicable): MSVC C++ 17.9.2
- Render backend (if applicable): none chosen

Configure and Build is performed with VS code

**Comment by Ravbug** [comment]
Thanks for the report! This is a known issue. There's a note on the readme about a workaround:
> On Windows, you will need to run your initial configure twice before building (known bug).

Unfortunately I don't know why this happens, or how to fix it. All I know is that something in PhysX's cmake configuration is causing it. Any insight would be appreciated.

**Comment by mPorst** [comment]
Ah I see, Previously I had an older MSVC version that complained about std::format not being supported. That hassled me a lot so after I finally updated the compiler, it is very possible that I forgot to configure twice.
Unfortunately I am not home this weekend so I don't have access to my windows computer. But I'll try it on monday then and also see if I can find out something about it :)

Thanks for the response ! I'm really looking forward to working with your engine :)

**Comment by mPorst** [comment]
Hello Ravbug, apparently the problem was not a missing configure. 
The first error hinted me that apparently the symbol "DxcBuffer" was not defined, so I installed the "gamedev for windows" extension for visual studio since I assumed previously I already had some DirectX version installed. This actually fixed the problem, I'd suggest to add this as a dependency to the readme since it doesn't list that.
I now get an exception on executing the samples however, though that would be an other issue. I'll first look into building everything with the vulkan backend since that was my preferred backend anyway :)
