### ISSUE TITLE
compile error under ubuntu22

### ISSUE THREAD

**Issue by zhangfq-chemistry** [RavEngine/RavEngine#28]
[ 69%] Built target RavEngineGUI
[ 69%] Generating RavEngineFlags_ShaderIntermediate/Vulkan/flag_special_fsh.spv
rvesc error: GLSL Parsing failed: ERROR: /home/zhangfq/2024/c++/Samples/Samples/Flags/shaders/flag_special.fsh:24: 'remap' : no matching overloaded function found 
ERROR: /home/zhangfq/2024/c++/Samples/Samples/Flags/shaders/flag_special.fsh:24: '' : compilation terminated 
ERROR: 2 compilation errors.  No code generated.

**Comment by Ravbug** [comment]
This has been fixed: https://github.com/RavEngine/Samples/actions/runs/10346868378/job/28636135037
