### ISSUE TITLE
Please support MSYS2 MINGW64

### ISSUE THREAD

**Issue by iahung** [RavEngine/RavEngine#6]

**Comment by Ravbug** [comment]
There are currently no plans to support MinGW.

What is your use case where you need this?

**Comment by iahung** [comment]
I'm using legacy Windows so I can't install MSVC. I'm stuck with MinGW.

**Comment by Ravbug** [comment]
Unless the Windows version you have supports DirectX 12 or Vulkan, RavEngine won't work on it. Supporting old systems is a non-goal for this project, sorry.

**Comment by iahung** [comment]
MSYS2 has support for Vulkan (and OpenGL, too).

**Comment by Ravbug** [comment]
That doesn't matter if your system doesn't have a new enough graphics driver that supports Vulkan.

What GPU, os version, and driver version do you have?

**Comment by iahung** [comment]
Very old hardware. So perhaps I'm out of luck.
