### ISSUE TITLE
set visibility

### ISSUE THREAD

**Issue by susgaming123** [RavEngine/RavEngine#7]
hey,

i dont know if this is implemented yet but is it possible to set visibility of 3d models?
i want to make a fps game with this engine and have it multiplayer and the third person character model needs to be invisible so i need a sort of thing like in unreal where it has OwnerNoSee and OnlyOwnerSee thing

**Comment by Ravbug** [comment]
You can use `StaticMesh::SetEnabled` and `SkinnedMeshComponent::SetEnabled` to toggle visibility of objects in a scene. Make sure to call it only on the main thread.

**Comment by susgaming123** [comment]
ah thanks! sorry for opening issues for questions do you have a discord server or something so i dont have to keep opening issues.

**Comment by Ravbug** [comment]
We have a [Discussion](https://github.com/RavEngine/RavEngine/discussions)(https://github.com/RavEngine/RavEngine/discussions) section which you can use for questions instead of opening Issues
